
import java.awt.event.ActionEvent;
import java.awt.event.ItemEvent;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.temporal.ChronoUnit;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class AplikasiPenghitungHari extends javax.swing.JFrame {

    /**
     * Creates new form AplikasiPenghitungHari
     */
    public AplikasiPenghitungHari() {
        initComponents();
    }
    
    private String HariBahasaIndo(java.time.DayOfWeek hari) {
        // Menggunakan switch case standar untuk kompatibilitas dengan NetBeans 8.2
        switch (hari) {
            case MONDAY:
                return "Senin";
            case TUESDAY:
                return "Selasa";
            case WEDNESDAY:
                return "Rabu";
            case THURSDAY:
                return "Kamis";
            case FRIDAY:
                return "Jumat";
            case SATURDAY:
                return "Sabtu";
            case SUNDAY:
                return "Minggu";
            default:
                return "";
        }
    }
    
  
     // Metode untuk memperbarui JComboBox dan JSpinner sesuai dengan tanggal yang dipilih pada JCalendar
    private void sinkronkanComboBoxDanSpinner() {
        java.util.Calendar cal = KalenderPenghitungHari.getCalendar();
        if (cal != null) {
            int bulan = cal.get(java.util.Calendar.MONTH);
            int tahun = cal.get(java.util.Calendar.YEAR);
            ComboBox1.setSelectedIndex(bulan);
            SpinnerTahun.setValue(tahun);
        }
    }
    
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LabelBulan = new javax.swing.JLabel();
        ComboBox1 = new javax.swing.JComboBox<>();
        SpinnerTahun = new javax.swing.JSpinner();
        LabelMasukkanTahun = new javax.swing.JLabel();
        KalenderPenghitungHari = new com.toedter.calendar.JCalendar();
        TombolHitung = new javax.swing.JButton();
        LabelHasilHitungHari = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        KalenderAwal = new com.toedter.calendar.JCalendar();
        KalenderAkhir = new com.toedter.calendar.JCalendar();
        TombolHitungSelisihHari = new javax.swing.JButton();
        LabelHasilSelisihHari = new javax.swing.JLabel();
        TombolKeluar = new javax.swing.JButton();
        TombolHapus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Penghitung Hari");

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Aplikasi Penghitung Hari");

        LabelBulan.setText("Pilih Bulan");

        ComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Februari", "Maret ", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        ComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboBox1ItemStateChanged(evt);
            }
        });

        SpinnerTahun.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SpinnerTahunStateChanged(evt);
            }
        });

        LabelMasukkanTahun.setText("Masukkan Tahun");

        KalenderPenghitungHari.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                KalenderPenghitungHariPropertyChange(evt);
            }
        });

        TombolHitung.setText("Hitung");
        TombolHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolHitungActionPerformed(evt);
            }
        });

        LabelHasilHitungHari.setText("Hasil : ");

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Perhitungan Selisih Hari");

        jLabel3.setText("Pilih Tanggal Awal");

        jLabel4.setText("Pilih Tanggal Akhir");

        TombolHitungSelisihHari.setText("Hitung ");
        TombolHitungSelisihHari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolHitungSelisihHariActionPerformed(evt);
            }
        });

        LabelHasilSelisihHari.setText("Hasil : ");

        TombolKeluar.setText("Keluar");
        TombolKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolKeluarActionPerformed(evt);
            }
        });

        TombolHapus.setText("Hapus");
        TombolHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolHapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(152, 152, 152))
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(KalenderAwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(KalenderAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(TombolHitungSelisihHari, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LabelHasilSelisihHari))
                .addContainerGap(105, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(TombolHapus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TombolKeluar)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelBulan)
                            .addComponent(LabelMasukkanTahun))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SpinnerTahun)
                            .addComponent(ComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(TombolHitung))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LabelHasilHitungHari)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(KalenderPenghitungHari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelBulan)
                            .addComponent(ComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SpinnerTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelMasukkanTahun))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TombolHitung)
                        .addGap(12, 12, 12)
                        .addComponent(LabelHasilHitungHari)
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(KalenderPenghitungHari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(KalenderAwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KalenderAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TombolHitungSelisihHari)
                .addGap(10, 10, 10)
                .addComponent(LabelHasilSelisihHari)
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TombolKeluar)
                    .addComponent(TombolHapus))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(76, 76, 76))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TombolHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolHitungActionPerformed
        // TODO add your handling code here:
        int tahun = (int) SpinnerTahun.getValue();
        int indexBulan = ComboBox1.getSelectedIndex() + 1;
        java.time.YearMonth ym = java.time.YearMonth.of(tahun, indexBulan);
        int hariDalamBulan = ym.lengthOfMonth();
        java.time.LocalDate hariPertama = ym.atDay(1);
        java.time.LocalDate hariTerakhir = ym.atEndOfMonth();
        boolean kabisat = java.time.Year.isLeap(tahun);
        String pesanKabisat = kabisat ? " (Tahun Kabisat)" : "";
        String hariAwal = HariBahasaIndo(hariPertama.getDayOfWeek());
        String hariAkhir = HariBahasaIndo(hariTerakhir.getDayOfWeek());
        String hasil = String.format(
                "Jumlah Hari: %d%s\nHari Pertama: %s\nHari Terakhir: %s",
                hariDalamBulan, pesanKabisat, hariAwal, hariAkhir
        );
        JOptionPane.showMessageDialog(this, hasil);
        LabelHasilHitungHari.setText("<html>Jumlah Hari: " + hariDalamBulan 
                             + "<br>Hari Pertama: " + hariAwal 
                             + "<br>Hari Terakhir: " + hariAkhir + "</html>");

    }//GEN-LAST:event_TombolHitungActionPerformed

    private void TombolHitungSelisihHariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolHitungSelisihHariActionPerformed
        // TODO add your handling code here:
        TombolHitungSelisihHari.addActionListener((ActionEvent e) -> {
            HitungSelisih();
        });
    }//GEN-LAST:event_TombolHitungSelisihHariActionPerformed

    private void SpinnerTahunStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SpinnerTahunStateChanged
        // TODO add your handling code here:
        SpinnerTahun.addChangeListener((ChangeEvent e) -> {
        PerbaruiKalender();
        });
    }//GEN-LAST:event_SpinnerTahunStateChanged

    private void TombolKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolKeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_TombolKeluarActionPerformed

    private void ComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboBox1ItemStateChanged
        // TODO add your handling code here:
         ComboBox1.addItemListener((ItemEvent e) -> {
            PerbaruiKalender();
        });
    }//GEN-LAST:event_ComboBox1ItemStateChanged

    private void TombolHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolHapusActionPerformed
        // TODO add your handling code here:
         TombolHapus.addActionListener((ActionEvent e) -> {
            HapusInputan();
        });
    }//GEN-LAST:event_TombolHapusActionPerformed

    private void KalenderPenghitungHariPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_KalenderPenghitungHariPropertyChange
        // TODO add your handling code here:
         sinkronkanComboBoxDanSpinner();
    }//GEN-LAST:event_KalenderPenghitungHariPropertyChange
     
    
    // Metode untuk menghitung selisih hari antara dua tanggal
    private void HitungSelisih() {
        // Mendapatkan tanggal awal dan akhir dari JCalendar
        Calendar startCal = KalenderAwal.getCalendar();
        Calendar endCal = KalenderAkhir.getCalendar();

        // Konversi Calendar ke LocalDate
        LocalDate startDate = startCal.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        LocalDate endDate = endCal.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

        // Menghitung selisih hari menggunakan ChronoUnit.DAYS
        long daysBetween = ChronoUnit.DAYS.between(startDate, endDate);
        

        // Menampilkan hasil selisih hari pada JLabel
        LabelHasilSelisihHari.setText(" Hasil Selisih hari antara dua tanggal: " + daysBetween + " hari");
    }
    
     private void PerbaruiKalender() {
        int month = ComboBox1.getSelectedIndex(); // Indeks bulan ComboBox mulai dari 0
        int year = (int) SpinnerTahun.getValue();

        // Mengatur KalenderPenghitungHari untuk bulan dan tahun yang dipilih
        Calendar selectedDate = Calendar.getInstance();
        selectedDate.set(Calendar.YEAR, year);
        selectedDate.set(Calendar.MONTH, month); // Calendar.MONTH juga mulai dari 0
        selectedDate.set(Calendar.DAY_OF_MONTH, 1);
        KalenderPenghitungHari.setCalendar(selectedDate); // Memperbarui tampilan JCalendar
    }

    // Metode untuk menghapus atau mereset pilihan
    private void HapusInputan() {
        // Reset bulan ke Januari
        ComboBox1.setSelectedIndex(0);

        // Reset tahun ke tahun default (misalnya 2023)
        SpinnerTahun.setValue(2023);

        // Reset KalenderPenghitungHari ke tanggal hari ini
        KalenderPenghitungHari.setCalendar(Calendar.getInstance());

        // Kosongkan hasil pada LabelHasilHitungHari
        LabelHasilHitungHari.setText("Jumlah hari: ");
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiPenghitungHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiPenghitungHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiPenghitungHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiPenghitungHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiPenghitungHari().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBox1;
    private com.toedter.calendar.JCalendar KalenderAkhir;
    private com.toedter.calendar.JCalendar KalenderAwal;
    private com.toedter.calendar.JCalendar KalenderPenghitungHari;
    private javax.swing.JLabel LabelBulan;
    private javax.swing.JLabel LabelHasilHitungHari;
    private javax.swing.JLabel LabelHasilSelisihHari;
    private javax.swing.JLabel LabelMasukkanTahun;
    private javax.swing.JSpinner SpinnerTahun;
    private javax.swing.JButton TombolHapus;
    private javax.swing.JButton TombolHitung;
    private javax.swing.JButton TombolHitungSelisihHari;
    private javax.swing.JButton TombolKeluar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
